### ISSUE TITLE
flutter run error: Error: The method 'FlushbarRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.

### ISSUE THREAD

**Issue by fauzipadlaw** [AndreHaueisen/flushbar#110]
Error message when running flutter run:
```
[+32498 ms] [+32508 ms] 
[        ]             Compiler message:
[        ] [   +2 ms] /C:/Users/fauzi/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flushbar-1.9.1/lib/flushbar_route.dart:273:8: Error: The method 'FlushbarRoute.install' has more
required arguments than those of overridden method 'OverlayRoute.install'.
[        ] [        ]   void install(OverlayEntry insertionPoint) {
[        ] [        ]        ^
[        ] [        ] /C:/src/flutter/packages/flutter/lib/src/widgets/routes.dart:40:8: Context: This is the overridden method ('install').
[        ] [        ]   void install() {
[        ] [        ]        ^
[+4594 ms] [+4590 ms] /C:/Users/fauzi/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flushbar-1.9.1/lib/flushbar_route.dart:281:18: Error: Too many positional arguments: 0 allowed,
but 1 found.
[   +1 ms] [        ] Try removing the extra positional arguments.
[        ] [        ]     super.install(insertionPoint);
[        ] [        ]                  ^
[+6798 ms] [+6801 ms] Persisting file store
[        ] [  +31 ms] Done persisting file store
[        ] [   +1 ms] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
[        ] build failed.
[        ] [  +10 ms] "flutter assemble" took 44,673ms.
[        ] #0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
[        ] #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:190:7)
[        ] <asynchronous suspension>
[        ] #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:639:18)
[        ] <asynchronous suspension>
[        ] #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:537:33)
[        ] <asynchronous suspension>
[        ] #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
[        ] #5      _rootRun (dart:async/zone.dart:1126:13)
[        ] #6      _CustomZone.run (dart:async/zone.dart:1023:19)
[   +1 ms] #7      _runZoned (dart:async/zone.dart:1518:10)
[   +1 ms] #8      runZoned (dart:async/zone.dart:1465:12)
[        ] #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
[        ] #10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:527:20)
[        ] #11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
[   +1 ms] #12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
[        ] <asynchronous suspension>
[        ] #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
[        ] #14     _rootRun (dart:async/zone.dart:1126:13)
[        ] #15     _CustomZone.run (dart:async/zone.dart:1023:19)
[  +15 ms] #16     _runZoned (dart:async/zone.dart:1518:10)
[   +1 ms] #17     runZoned (dart:async/zone.dart:1465:12)
[        ] #18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
[        ] #19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
[        ] #20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
[   +1 ms] #21     new Future.sync (dart:async/future.dart:224:31)
[        ] #22     CommandRunner.run (package:args/command_runner.dart:112:14)
[        ] #23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
[        ] #24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
[        ] #25     _rootRun (dart:async/zone.dart:1126:13)
[        ] #26     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #27     _runZoned (dart:async/zone.dart:1518:10)
[        ] #28     runZoned (dart:async/zone.dart:1502:12)
[        ] #29     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
[        ] <asynchronous suspension>
[        ] #30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
[        ] #31     _rootRun (dart:async/zone.dart:1126:13)
[        ] #32     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #33     _runZoned (dart:async/zone.dart:1518:10)
[        ] #34     runZoned (dart:async/zone.dart:1465:12)
[        ] #35     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
[        ] #36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
[        ] #37     run (package:flutter_tools/runner.dart:51:10)
[        ] #38     main (package:flutter_tools/executable.dart:65:9)
[        ] #39     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
[        ] #40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
[        ] #41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
[  +51 ms] > Task :app:compileFlutterBuildDebug FAILED
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[        ] Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 803
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 2s
[   +4 ms] See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 1 actionable task: 1 executed
[ +411 ms] Running Gradle task 'assembleDebug'... (completed in 63.7s)
[   +7 ms] "flutter run" took 73,207ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:394:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.14.7-pre.38, on Microsoft Windows [Version 10.0.17134.950], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.41.1)
[√] VS Code, 64-bit edition (version 1.41.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by valterh4ck3r** [comment]
Fixed on PR https://github.com/AndreHaueisen/flushbar/pull/111

**Comment by Condelab** [comment]
so how d

> Fixed on PR #111

so how does it affect the pub version, and how long do we have to wait :)

**Comment by sc4v3ng3r** [comment]
I am also getting this error.

**Comment by ZepSaxis** [comment]
Workaround, for now,  is to switch to beta channel.

**Comment by Condelab** [comment]
> Workaround, for now, is to switch to beta channel.

how? pls!

**Comment by ZepSaxis** [comment]
From your terminal:

"flutter channel beta"

then

"flutter upgrade"

**Comment by Condelab** [comment]
> flutter upgrade

so sorry to ask...but are u saying that to use this plugin my whole project has to switch to beta channel, well i did that and other stfuz like `Theme.of(context).textTheme.headline4` brings error `the getter headlin4 isn't defined or the class textTheme`.

**Comment by ZepSaxis** [comment]
No, I'm saying this worked for me.  I don't need to be on the master channel for my project.

**Comment by Condelab** [comment]
OH! OK. thanks all the same! do you know what this error means and its source in the code, may be I could just fork it or something?

**Comment by ZepSaxis** [comment]
If I absolutely couldn't wait, then yes, I would fork it with the applied PR (#110 ) mentioned above..

**Comment by Condelab** [comment]
thanks once again!

**Comment by valterh4ck3r** [comment]
Use my fork if that you need. 

https://github.com/valterh4ck3r/flushbar

**Comment by Hassan-Fa** [comment]
+1 for merge :D

**Comment by alizera** [comment]
I face this issue on package's version 1.9.1 and flutter's version 1.12.13 and there is no update for package yet :(

**Comment by omar-khaium** [comment]
try `flushbar: 1.6.0`
It workes for me. Also, check the changelogs for the compatible version for you.

**Comment by bsutton** [comment]
So is there going to be a release?

I've got the same error with flushbar 1.10

**Comment by jjov** [comment]
> try `flushbar: 1.6.0`
> It workes for me. Also, check the changelogs for the compatible version for you.

It worked for me meanwhile this can be fixed for newer versions

**Comment by cahyowhy** [comment]
> Use my fork if that you need.
> 
> https://github.com/valterh4ck3r/flushbar

your fork didnt work on my env
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git

**Comment by jrmessias** [comment]
error in Flutter 1.12.13+hotfix.8 • channel stable

**Comment by erfanegtfi** [comment]
I've got the error with flushbar 1.10
Flutter 1.12.13+hotfix.9
```
Compiler message:
../../AppData/Roaming/Pub/Cache/git/flushbar-13c55a888c1693f1c8269ea30d55c614a1bfee16/lib/flushbar_route.dart:273:8: Error: The method 'FlushbarRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
  void install() {
       ^
/C:/src/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install(OverlayEntry insertionPoint) {
       ^
../../AppData/Roaming/Pub/Cache/git/flushbar-13c55a888c1693f1c8269ea30d55c614a1bfee16/lib/flushbar_route.dart:281:18: Error: Too few positional arguments: 1 required, 0 given.
    super.install();
                 ^
```

**Comment by bambury** [comment]
> I've got the error with flushbar 1.10
> Flutter 1.12.13+hotfix.9
> 
> ```

If you are using Flutter <1.15, you should stay on flushbar 1.9.1

**Comment by hak24** [comment]
Same error
Using Flutter 1.12.13+hotfix.9
None of the old versions of flushbar is working for me

**Comment by bambury** [comment]
I am also using 1.12.13+hotfix.9 and flushbar 1.9.1 works for me.
Just make sure you're using that exact version ("flushbar: 1.9.1", not   "flushbar: ^1.9.1") in pubspec.yaml and run "flutter pub get" and "flutter clean". That's all I can suggest.

**Comment by hak24** [comment]
> I am also using 1.12.13+hotfix.9 and flushbar 1.9.1 works for me.
> Just make sure you're using that exact version ("flushbar: 1.9.1", not "flushbar: ^1.9.1") in pubspec.yaml and run "flutter pub get" and "flutter clean". That's all I can suggest.

removing ^ from ^1.9.1 worked. Thanks.

**Comment by mrm2004** [comment]
> > I am also using 1.12.13+hotfix.9 and flushbar 1.9.1 works for me.
> > Just make sure you're using that exact version ("flushbar: 1.9.1", not "flushbar: ^1.9.1") in pubspec.yaml and run "flutter pub get" and "flutter clean". That's all I can suggest.
> 
> removing ^ from ^1.9.1 worked. Thanks.

Version 1.10.0 is giving me the same error, the only solution was to move to 1.9.1 without "ˆ", thanks

**Comment by jabershabeek** [comment]
Yup!! only option is to use 1.9.1, without getting the minor/patch updates(no ^)

**Comment by bambury** [comment]
Yep. It's actually documented in the [changelog](https://github.com/AndreHaueisen/flushbar/commit/b9908e2590270bd742e17c4d906d7056077b051f#diff-4ac32a78649ca5bdd8e0ba38b7006a1e).
As a personal note, I think version 1.10 of flushbar should be version 2.0, to match the before/after situation Flutter created with the breaking change.

**Comment by rafiqulislam21** [comment]
> I am also using 1.12.13+hotfix.9 and flushbar 1.9.1 works for me.
> Just make sure you're using that exact version ("flushbar: 1.9.1", not "flushbar: ^1.9.1") in pubspec.yaml and run "flutter pub get" and "flutter clean". That's all I can suggest.

Thanks. It workes for me.

**Comment by jogapps** [comment]
Thank you. Its working now

**Comment by imSanjaySoni** [comment]
I am also using 1.12.13+hotfix.9 and flushbar 1.9.1 works for me.

**Comment by joaovirgili** [comment]
I'm getting this error after upgrade flutter to 1.17 and flushbar 1.9.1. Also tried flushbar ^1.10.2 Any solution?

**Comment by howieweiner** [comment]
> I'm getting this error after upgrade flutter to 1.17 and flushbar 1.9.1. Also tried flushbar ^1.10.2 Any solution?

1.10.2 works for me with flutter 1.17. Try flutter clean

**Comment by rafiqulislam21** [comment]
After upgrading 1.17 stable, flushbar: 1.10.0 works for me

**Comment by joaovirgili** [comment]
> > I'm getting this error after upgrade flutter to 1.17 and flushbar 1.9.1. Also tried flushbar ^1.10.2 Any solution?
> 
> 1.10.2 works for me with flutter 1.17. Try flutter clean

Worked for me, thanks.

**Comment by lemidiriba** [comment]
Edit
flushbar-1.9.1/lib/flushbar_route.dart

Line 273
void install() {

And line 281
super.install();

check this link
[](https://github.com/AndreHaueisen/flushbar/issues/113) https://github.com/AndreHaueisen/flushbar/issues/113

**Comment by bruno-c-nogueira** [comment]
flushbar: ^1.10.2

its gonna work
