### ISSUE TITLE
Error: Type 'Completer' not found. Error in latest flutter version : Flutter 1.17.0 • channel stable

### ISSUE THREAD

**Issue by sarinupreti** [AndreHaueisen/flushbar#130]
```

Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:290:3: Error: Type 'Completer' not found.
  Completer<Size> _boxHeightCompleter;
  ^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:290:3: Error: Expected 0 type arguments.
  Completer<Size> _boxHeightCompleter;
  ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:290:3: Error: 'Completer' isn't a type.
  Completer<Size> _boxHeightCompleter;
  ^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:299:27: Error: The method 'Completer' isn't defined for the class '_FlushbarState<K>'.
 - '_FlushbarState' is from 'package:flushbar/flushbar.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Completer'.
    _boxHeightCompleter = Completer<Size>();
                          ^^^^^^^^^

```

flutter doctor

```
$ flutter doctor -v
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale en-US)  
    • Flutter version 1.17.0 at C:\Users\sarin\Documents\flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Program Files\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Program Files\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\sarin\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\sarin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator) 
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.163    
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by sarinupreti** [comment]
`[ +361 ms] [+1436 ms] 
[        ]            Compiler message:
[        ] [   +1 ms]
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:290:3: Error: Type
'Completer' not found.
[   +1 ms] [        ]   Completer<Size> _boxHeightCompleter;
[        ] [        ]   ^^^^^^^^^
[        ] [   +2 ms]
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:290:3: Error: Expected 0   
type arguments.
[        ] [        ]   Completer<Size> _boxHeightCompleter;
[        ] [        ]   ^
[+2092 ms] [+2053 ms]
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:290:3: Error: 'Completer'  
isn't a type.
[   +2 ms] [        ]   Completer<Size> _boxHeightCompleter;
[   +1 ms] [        ]   ^^^^^^^^^
[        ] [   +3 ms]
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:299:27: Error: The method  
'Completer' isn't defined for the class '_FlushbarState<K>'.
[  +12 ms] [        ]  - '_FlushbarState' is from 'package:flushbar/flushbar.dart'
('../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart').
[   +1 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named   
'Completer'.
[   +1 ms] [        ]     _boxHeightCompleter = Completer<Size>();
[  +12 ms] [        ]                           ^^^^^^^^^
[+3767 ms] [+3782 ms] package:fonepay_offer_app/main.dart: Error: No 'main' method found.
[   +1 ms] [        ] Try adding a method named 'main' to your program.
[        ] [        ] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
[  +12 ms] build failed.
[   +1 ms] #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[  +15 ms] #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:202:7)
[   +1 ms] #2      _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] #3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)      
[   +1 ms] #6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[  +12 ms] #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[   +1 ms] #10     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[  +11 ms] #11     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +1 ms] #12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[  +12 ms] [  +51 ms] Persisting file store
[   +1 ms] [   +7 ms] Done persisting file store
[        ] [   +7 ms] "flutter assemble" took 7,507ms.
[  +11 ms] #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[  +11 ms] #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[        ] #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)     
[  +11 ms] #20     _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] #21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #22     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)      
[        ] #24     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #25     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[  +12 ms] #26     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
[   +1 ms] #27     _rootRunUnary (dart:async/zone.dart:1192:38)
[  +12 ms] #28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] #29     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)      
[  +11 ms] #31     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #32     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[  +12 ms] #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[   +1 ms] #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[   +1 ms] #35     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)  
[  +12 ms] #36     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
[   +1 ms] #37     _rootRunBinary (dart:async/zone.dart:1204:38)
[  +13 ms] #38     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
[  +12 ms] #39     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
[   +1 ms] #40     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
[  +12 ms] #41     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
[   +1 ms] #42     Future._completeError (dart:async/future_impl.dart:534:5)
[  +12 ms] #43     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
[   +1 ms] #44     KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart)
[  +12 ms] #45     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +1 ms] #46     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #47     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[  +12 ms] #48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #49     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #50     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[  +12 ms] #51     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[  +13 ms] #52     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[   +1 ms] #53     KernelCompiler.compile (package:flutter_tools/src/compile.dart)
[        ] #54     _rootRunUnary (dart:async/zone.dart:1192:38)
[  +12 ms] #55     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[  +24 ms] #56     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[   +1 ms] #57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)      
[        ] #58     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #59     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #60     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
[        ] #61     _rootRun (dart:async/zone.dart:1184:13)
[        ] #62     _CustomZone.run (dart:async/zone.dart:1077:19)
[  +12 ms] #63     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[   +1 ms] #64     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
[  +11 ms] #65     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[   +1 ms] #66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[        ] #67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[  +12 ms] #68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[  +24 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'C:\Users\sarin\Documents\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882   
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDevDebug'.
[        ] > Process 'command 'C:\Users\sarin\Documents\flutter\bin\flutter.bat'' finished with non-zero exit 
value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more 
log output. Run with --scan to get full insights.
[  +24 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 12s`

**Comment by sarinupreti** [comment]
```
[ +361 ms] [+1436 ms] 
[        ]            Compiler message:
[        ] [   +1 ms]
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:290:3: Error: Type
'Completer' not found.
[   +1 ms] [        ]   Completer<Size> _boxHeightCompleter;
[        ] [        ]   ^^^^^^^^^
[        ] [   +2 ms]
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:290:3: Error: Expected 0   
type arguments.
[        ] [        ]   Completer<Size> _boxHeightCompleter;
[        ] [        ]   ^
[+2092 ms] [+2053 ms]
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:290:3: Error: 'Completer'  
isn't a type.
[   +2 ms] [        ]   Completer<Size> _boxHeightCompleter;
[   +1 ms] [        ]   ^^^^^^^^^
[        ] [   +3 ms]
../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart:299:27: Error: The method  
'Completer' isn't defined for the class '_FlushbarState<K>'.
[  +12 ms] [        ]  - '_FlushbarState' is from 'package:flushbar/flushbar.dart'
('../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar.dart').
[   +1 ms] [        ] Try correcting the name to the name of an existing method, or defining a method named   
'Completer'.
[   +1 ms] [        ]     _boxHeightCompleter = Completer<Size>();
[  +12 ms] [        ]                           ^^^^^^^^^
[+3767 ms] [+3782 ms] package:fonepay_offer_app/main.dart: Error: No 'main' method found.
[   +1 ms] [        ] Try adding a method named 'main' to your program.
[        ] [        ] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
[  +12 ms] build failed.
[   +1 ms] #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[  +15 ms] #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:202:7)
[   +1 ms] #2      _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] #3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)      
[   +1 ms] #6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[  +12 ms] #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[   +1 ms] #10     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[  +11 ms] #11     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +1 ms] #12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[  +12 ms] [  +51 ms] Persisting file store
[   +1 ms] [   +7 ms] Done persisting file store
[        ] [   +7 ms] "flutter assemble" took 7,507ms.
[  +11 ms] #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[  +11 ms] #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[        ] #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)     
[  +11 ms] #20     _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] #21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #22     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)      
[        ] #24     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #25     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[  +12 ms] #26     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
[   +1 ms] #27     _rootRunUnary (dart:async/zone.dart:1192:38)
[  +12 ms] #28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] #29     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)      
[  +11 ms] #31     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #32     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[  +12 ms] #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[   +1 ms] #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[   +1 ms] #35     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)  
[  +12 ms] #36     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
[   +1 ms] #37     _rootRunBinary (dart:async/zone.dart:1204:38)
[  +13 ms] #38     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
[  +12 ms] #39     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
[   +1 ms] #40     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
[  +12 ms] #41     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
[   +1 ms] #42     Future._completeError (dart:async/future_impl.dart:534:5)
[  +12 ms] #43     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
[   +1 ms] #44     KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart)
[  +12 ms] #45     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +1 ms] #46     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] #47     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[  +12 ms] #48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #49     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #50     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[  +12 ms] #51     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[  +13 ms] #52     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[   +1 ms] #53     KernelCompiler.compile (package:flutter_tools/src/compile.dart)
[        ] #54     _rootRunUnary (dart:async/zone.dart:1192:38)
[  +12 ms] #55     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[  +24 ms] #56     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[   +1 ms] #57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)      
[        ] #58     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #59     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #60     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
[        ] #61     _rootRun (dart:async/zone.dart:1184:13)
[        ] #62     _CustomZone.run (dart:async/zone.dart:1077:19)
[  +12 ms] #63     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[   +1 ms] #64     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
[  +11 ms] #65     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[   +1 ms] #66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[        ] #67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[  +12 ms] #68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[  +24 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'C:\Users\sarin\Documents\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882   
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDevDebug'.
[        ] > Process 'command 'C:\Users\sarin\Documents\flutter\bin\flutter.bat'' finished with non-zero exit 
value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more 
log output. Run with --scan to get full insights.
[  +24 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 12s

```

**Comment by sarinupreti** [comment]
found a solution  change to this in your pubspec.yaml

```
flushbar:
    git:
      url: git://github.com/valterh4ck3r/flushbar
      ref: master

```
