### ISSUE TITLE
Flushbar not showing when making it r

### ISSUE THREAD

**Issue by ashihCT** [AndreHaueisen/flushbar#37]
**Describe the bug**
If I show a basic `Flushbar` it shows properly. As soon as I add `aroundPadding` and `borderRadius`, it throws an error. I am running on iOS and using a `CupertinoPageScaffold`.

**Paste relevant code**

```
Flushbar(
                title:  "Subscribed",
                message:  "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                aroundPadding: EdgeInsets.all(8),
                borderRadius: 8,
                duration:  Duration(seconds: 2),
              ).show(context);
```

When the exception was thrown, this was the stack:

```
flutter: #0      new Flushbar (package:flushbar/flushbar.dart:375:27)
flutter: #1      _ArtistDetailState.subscribeWidget.<anonymous closure> (package:schedule/artist_detail_widget.dart:309:15)
flutter: #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
flutter: #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
flutter: #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
flutter: #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
flutter: #6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
flutter: #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
flutter: #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
flutter: #18     _invoke1 (dart:ui/hooks.dart:223:10)
flutter: #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
```

**Comment by AndreHaueisen** [comment]
Hi @ashihCT 
I was able to reproduce it here and it is probably a Flutter bug. I will investigate it further and open an issue if that is the case.
The problem is actually only with `borderRadius`. Some gesture detector problem it seems.
For now, just avoid using it.
Thanks for the bug repport.

**Comment by AndreHaueisen** [comment]
https://github.com/flutter/flutter/issues/30067

**Comment by AndreHaueisen** [comment]
Ok. That is embarrassing. Simply use a double instead of an int. Will push an update to avoid this problem today.

**Comment by ashihCT** [comment]
works great. thanks Andre!
